title:              AbdielS Blog
email:              abdiels@gmail.com
description:        Adventures and thoughts about software development
author:             Abdiel E. Sanchez
baseurl:            
url:                "https://abdiels.github.io"

# Social Profiles
twitter_username:   AbdielSR
github_username:    abdiels
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-F1GX4PX0F3 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
